### ISSUE TITLE
404 - Unable to process the page 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by gnurizen** [binaryage/drydrop#24]
I'm getting this error from one of my custom domains but not the appspot.com domain.   Another custom domain works.   So:

www.gnurizen.me - doesn't work, python error 
foo.gnurizen.me - works!
gnurizen.appspot.com - works!

How do I go about debugging this python error?   I'm new to GAE but know python well.   I tried re-uploading the app but that didn't help.

**Comment by gnurizen** [comment]
By going in the GAE db admin and deleting all the resources/settings entities its working now.  This was the error:

Traceback (most recent call last):
  File "/base/data/home/apps/s~gnurizen/master.357023081167493973/drydrop_handler.py", line 307, in route
    dispatched = self.meta_dispatch(self.settings.source, config_source, self.request.path, self.request.headers, self.request.environ)
  File "/base/data/home/apps/s~gnurizen/master.357023081167493973/drydrop_handler.py", line 123, in meta_dispatch
    config, matcher = ParseAppConfig(self.settings.source, config_source, self.vfs, static_caching=True)
  File "drydrop.zip/drydrop/app/meta/server.py", line 873, in ParseAppConfig
    vfs)
  File "drydrop.zip/drydrop/app/meta/server.py", line 819, in CreateURLMatcherFromMaps
    for url_map in url_map_list:
TypeError: 'NoneType' object is not iterable

**Comment by darwin** [comment]
good you have resolved it, I haven't been doing any GAE work lately, so I couldn't help anyway.
