### ISSUE TITLE
Having Problems trying to deploy drydrop

### ISSUE THREAD

**Issue by robot-c0der** [binaryage/drydrop#6]
Hi, sorry if this has nothing to do with drydrop and your code but every time i try to run 
    rake upload project=namehere

 i get the following error

```
/usr/local/bin/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
os.path.join(DIR_PATH, 'lib', 'django'),
/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
import md5
Traceback (most recent call last):
  File "/usr/local/bin/appcfg.py", line 69, in <module>
  run_file(__file__, globals())
  File "/usr/local/bin/appcfg.py", line 65, in run_file
execfile(script_path, globals_)
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 3100, in <module>
main(sys.argv)
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 3091, in main
  result = AppCfgApp(argv).Run()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 2013, in Run
self.action(self)
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 2943, in __call__
return method()
 File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 2344, in Update
appyaml = self._ParseAppYaml(basepath, includes=True)
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appcfg.py", line 2208, in _ParseAppYaml
appyaml = appinfo_includes.Parse(fh)
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/appinfo_includes.py", line 51, in Parse
'No URLMap entries found in application configuration')
google.appengine.api.appinfo_errors.MissingURLMapping: No URLMap entries found in application configuration
```

i know it's kinda messy to read, i apologize for that but i copied and pasted it from the terminal window. Any help with this would be greatly appreciated seeing as i have absolutely no idea what is going on here..

**Comment by darwin** [comment]
This is some problem reported by appcfg.py, it says: 
`No URLMap entries found in application configuration`

check your app.yaml:
http://code.google.com/appengine/docs/python/config/appconfig.html
